-- MySQL Script generated by MySQL Workbench
-- Mon May 29 14:04:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema building_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema building_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `building_company` DEFAULT CHARACTER SET utf8 ;
USE `building_company` ;

-- -----------------------------------------------------
-- Table `building_company`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `building_company`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `building_company`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `building_company`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `cost` INT NULL,
  `clients_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_clients1_idx` (`clients_id` ASC) VISIBLE,
  INDEX `fk_projects_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `building_company`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `building_company`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `hire_date` DATE NULL,
  `phone_number` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_address1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_employees_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `building_company`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `building_company`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `building_company`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `quantity` INT NULL,
  `cost` INT NULL,
  `suppliers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materials_suppliers1_idx` (`suppliers_id` ASC) VISIBLE,
  CONSTRAINT `fk_materials_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `building_company`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`equipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `quantity` INT NULL,
  `cost` INT NULL,
  `suppliers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipment_suppliers1_idx` (`suppliers_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `building_company`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`materials_in_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`materials_in_project` (
  `materials_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`materials_id`, `project_id`),
  INDEX `fk_materials_has_project_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_materials_has_project_materials1_idx` (`materials_id` ASC) VISIBLE,
  CONSTRAINT `fk_materials_has_project_materials1`
    FOREIGN KEY (`materials_id`)
    REFERENCES `building_company`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `building_company`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`equipment_in_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`equipment_in_project` (
  `equipment_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`equipment_id`, `project_id`),
  INDEX `fk_equipment_has_project_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_equipment_has_project_equipment1_idx` (`equipment_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_has_project_equipment1`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `building_company`.`equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `building_company`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
